Repository mlcommons/inference, pull requests merged in 2024-10, with the labels that each got.

#1853 Fix docs
  docs/install/index.md
  main.py
Labels: documentation

#1851 Fix typo in reference datatype
  language/llama2-70b/README.md
Labels: documentation

#1512 Fix link in GettingStarted.ipynb
  vision/classification_and_detection/GettingStarted.ipynb
Labels: documentation

#1449 Tflite tpu
  vision/classification_and_detection/python/backend_tflite.py
  vision/classification_and_detection/python/dataset.py
  vision/classification_and_detection/python/main.py
  vision/classification_and_detection/run_common.sh
  vision/classification_and_detection/run_local.sh
  vision/classification_and_detection/tools/install_edgetpu_compiler.sh
  vision/classification_and_detection/tools/resnet50_tflite_edgetpu.py
Labels: new-backend

#1882 [Postmortem 4.1] Make mlperf.conf static in loadgen, enable automatic Pypi release
  .github/workflows/build_wheels.yml
  .github/workflows/test-bert.yml
  .github/workflows/test-loadgen.yml
  .github/workflows/test-resnet50.yml
  .github/workflows/test-retinanet.yml
  language/bert/run.py
  language/gpt-j/main.py
  language/llama2-70b/main.py
  language/mixtral-8x7b/main.py
  loadgen/CMakeLists.txt
  loadgen/MANIFEST.in
  loadgen/VERSION.txt
  loadgen/__init__.py
  loadgen/benchmark/repro.cpp
  loadgen/bindings/python_api.cc
  loadgen/mlperf.conf
  loadgen/pyproject.toml
  loadgen/results.h
  loadgen/setup.py
  loadgen/test_settings.h
  loadgen/test_settings_internal.cc
  mlperf.conf
  recommendation/dlrm_v2/pytorch/python/main.py
  text_to_image/main.py
  vision/classification_and_detection/python/main.py
  vision/classification_and_detection/run_local.sh
Labels: postmortem 4.1

#1886 Update evaluation.py | Output GPTJ accuracy metric as string
  language/gpt-j/evaluation.py
Labels: bug-fix

#1875 Update format.yml | Improve the github action
  .github/scripts/format-cpp.sh
  .github/scripts/format-py.sh
  .github/workflows/format.yml
  language/bert/accuracy-squad.py
Labels: bug-fix

#1881 Update submission_checker.py | mixtral is not having singlestream sce…
  tools/submission/submission_checker.py
Labels: bug-fix

#1887 Removed mlperf.conf check in submission checker, removed equal issue …
  .github/workflows/build_wheels.yml
  .github/workflows/test-resnet50.yml
  .github/workflows/test-submission-checker.yml
  loadgen/CMakeLists.txt
  loadgen/MANIFEST.in
  loadgen/VERSION.txt
  loadgen/__init__.py
  loadgen/setup.py
  loadgen/test_settings_internal.cc
  loadgen/version_generator.py
  tools/submission/preprocess_submission.py
  tools/submission/submission_checker.py
Labels: postmortem 4.1
